### ISSUE TITLE
težava pri kodi

### ISSUE THREAD

**Issue by TrafelaT18** [TrafelaT18/Optimalna-strategija-crpanja-in-skladiscenja-nafte#2]
Pozdravljeni, imava težave s kodo. Medve želiva ugotoviti optimalno strategijo črpanja in prodajanja nafte, imava pa tudi možnost shranjevanja nafte. Rešitve pravijo, da vsakič vse načrpava in vse prodava, nikoli pa nič ne shraniva ali prodava zaloge (ki jih  pri nama ni). Zato naju zanima, kaj nama manjka v kodi, da bi se kaj nafte tudi shranilo in prodalo iz zalog.

**Comment by jaanos** [comment]
Vidim, da sta diskretizirali tudi količine načrpane/prodane/skladiščene nafte - to je načeloma v redu, saj lahko predpostavita, da je osnovna enota sodček in nikoli ne obravnavata količin, ki niso celoštevilsko število sodčkov.

Je pa v kodi nekaj problemov. Prvič, količina skladiščene nafte konec vsakega dne je vhodna spremenljivka pri rekurzivni funkciji - računata torej optimalne dobičke, če dan `i` končata z `x` sodčki načrpane nafte, in sicer za vse `i` in vse `x`. Šele na koncu, ko izračunata optimalen dobiček za zadnji dan, lahko gresta nazaj po rešitvi in rekonstruirata količino načrpane/prodane/skladiščene nafte za vsak dan. Poleg tega bo potrebno za vsak dan in skladiščeno količino na novo graditi seznam potencialnih rešitev.

Popravljena koda bi izgledala nekako takole. Dodal sem še možnost spreminjanja prodajnih cen ter primer, pri katerem se načrpana nafta prva dva dni skladišči, nato pa se tretji dan vse proda:
```python
def nafta(K, dni, P, S, STRc, STRs):
    # npr. nafta(10, 3, [10, 20, 30], 40, [5, 10, 7], [3, 4, 9])
    inf = float('inf') # neskončnost
    d = {(0, 0): 0} # slovar optimalnih dobičkov - začnemo brez zaloge in dobička
    p = {(0, 0): None} # slovar parametrov - kako smo prišli do optimalnega dobička
    for i in range(dni): # za vsak dan od 1 naprej
        for x in range(S+1): # končna zaloga dne i
            kandidati = [(-inf, (0, 0, 0))] # seznam dobičkov - začnemo z -inf
            for Qi in range(K+1): # koliko izčrpamo <= K
                for Qp in range(max(0, Qi - x), S + Qi - x + 1): # koliko prodamo >= koliko izčrpamo - končna zaloga = višek, <= kapaciteta + višek
                    x_prev = x + Qp - Qi # zaloga iz prejšnjega dne
                    ix_prev = (i, x_prev) # podatki za prejšnji dan
                    if ix_prev in d: # preverimo, ali imamo podatke za prejšnji dan
                        di = P[i] * Qp - STRc[i] * Qi - STRs[i] * x + d[ix_prev] # skupni dobiček
                        kandidati.append((di, (Qi, Qp, x_prev))) # dodamo skupni dobiček in parametre med kandidate
            M, par = max(kandidati) # dobimo maksimalni skupni dobiček
            d[i+1, x] = M # shranimo maksimalni dobiček
            p[i+1, x] = par # shranimo parametre za maksimalni dobiček
    return (d[dni, 0], p) # optimalni dobiček in parametri za rekonstrukcijo
```
Podatki za rekonstrukcijo rešitve se nahajajo v slovarju `p`. Sedaj gresta lahko po dnevih nazaj ter pri vsakem dobita parametre (izčrpana nafta, prodana nafta, začetna zaloga = končna zaloga prejšnjega dne), ki jih lahko vrneta v seznamu.
